### ISSUE TITLE
同楼上启动了接口返回空数组

### ISSUE THREAD

**Issue by ysysycyc** [ZhaoYueNing/lightmerge#9]
看了下代码没有找到给GitProjectRepository.projectMap赋值的地方，请教下是怎么实现的呢

**Comment by ZhaoYueNing** [comment]
由于文档指导错误 ，将projects 配置改为 projectMap ，同 #8

**Comment by ZhaoYueNing** [comment]
问题已经修复，请重新下载0.2版本的包，原因是set 和 get名不一致导致的
